name: Build - Docker image (SemVer)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs: 
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: DockerHub login
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        if: env.DOCKER_HUB_USER == ''
        uses: docker/login-action@v2
        with:
          # Use existing DockerHub credentials present as secrets
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
