name: Build - Docker image (SemVer)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs: 
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          # Use existing DockerHub credentials present as secrets
          #username: ${{ secrets.DOCKER_HUB_USER }}
          username: ''
          #password: ${{ secrets.DOCKER_HUB_TOKEN }}
          password: ${{ secrets.FOCKER_HUB_TOKEN }}
